FROM php:7.4-apache

WORKDIR /var/www/html
COPY index.php /var/www/html/
COPY conexao.php /var/www/html/

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-edv \
    && docker-php-ext-configuregd --with-feetype --with-jpeg \
    && docker-php-ext-install -js(nproc) gd \
    && docker-php-install mysqli

EXPOSE 80